### ISSUE TITLE
Проблема при создании 2 аккаунта

### ISSUE THREAD

**Issue by 2taras** [alryaz/hass-mosenergosbyt#1]
Определяет объекты правильно а их состояние нет

**Comment by 2taras** [comment]
![Без имени](https://user-images.githubusercontent.com/63609624/83952443-95ee8980-a841-11ea-9d77-3bb9a64a4339.png)

**Comment by 2taras** [comment]
![Без имени](https://user-images.githubusercontent.com/63609624/83952524-13b29500-a842-11ea-91ee-ac16121eaf03.png)

**Comment by alryaz** [comment]
На данный момент такая работа не поддерживается, но в ближайшее время (в течение одного-пяти дней) напишу обновление, переводящее весь модуль на асинхронную работу, и поддерживающее несколько пользователей (пока что несколько лицевых счетов устроить не удаётся, потому что не получается устроить тестовую среду).

**Comment by alryaz** [comment]
Прошу протестировать загруженную версию.
К слову, добавлять аккаунты следует вот так:
```yaml
mosenergosbyt:
  - username: a_user
    password: a_pass
  - username: b_user
    password: b_pass
```
