### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by barskaka** [alryaz/hass-mosenergosbyt#5]
Home Assistant 0.114.0 в Docker
После ввода логина\пароля, интеграция выдаёт ошибку "Unknown error occurred"
Добавление вручную не помогает. Интеграция появляется в списке, но вход в ЛК не происходит

**Comment by msslava** [comment]
Та же самая ошибка

**Comment by alryaz** [comment]
Включите DEBUG-логгинг:
```yaml
# configuration.yaml
logger:
  logs:
    custom_components.mosenergosbyt: debug
```

Перезапустите HA, и пришлите логи с момента запуска Home Assistant до выявления проблемы на почту `alryaz@xavux.com` (логи будут содержать конфиденциальную информацию, предупреждаю).
